# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: echo Pipeline
  displayName: 'Run a one-line script'
- script: pwsh -Command {Install-Module Plaster -Force}
  displayName: 'Install Plaster'
- script: pwsh -Command {Install-Module Pester -Force}
  displayName: 'Install Pester'
- script: pwsh -File test.ps1
  displayName: 'Run test.ps1 script'